# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bcms_cas}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BrowserMedia"]
  s.date = %q{2010-01-18}
  s.email = %q{github@browsermedia.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "app/models/cas_user.rb",
     "app/portlets/helpers/login_portlet_helper.rb",
     "db/migrate/20091002162550_add_cas_user_group.rb",
     "lib/bcms_cas.rb",
     "lib/bcms_cas/routes.rb",
     "lib/cas/authentication.rb",
     "lib/cas/login_portlet_extension.rb",
     "lib/cas/utils.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://browsercms.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{browsercms}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A CAS Module for BrowserCMS}
  s.test_files = [
    "test/performance/browsing_test.rb",
     "test/test_helper.rb",
     "test/unit/cas/cas_authentication_test.rb",
     "test/unit/cas/login_portlet_test.rb",
     "test/unit/cas_user_test.rb",
     "test/unit/cas_utils_test.rb",
     "test/unit/helpers/login_portlet_helper_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

